plugins:
  discourse_mailchimp_webhook_enabled:
    default: true
  mailchimp_list_id:
    default: '1234567890'
  mailchimp_api_key:
    default: ''
  mailchimp_dc:
    default: 'us10'
  mailchimp_user_field:
    default: ''
    client: true
